# Generated by Django 6.0.7 on 2026-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='ml_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='ml_prediction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
