# Generated by Django 6.0.7 on 2026-07-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_company_email_company_company_phone_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='office_location',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='companies.company'),
        ),
    ]
